spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phonestore_db
    username: phonestore
    password: 2029
  jpa:
   properties:
    hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
   hibernate:
    ddl-auto: update